---
title: "Sample Data EDA"
output: github_document
---

## Data Structure

This repository contains a `sample_breaches.csv` data file containing cyber 
breach information (this is simulated data, not live customer information). The 
schema for the file is:

column | description |
-------|-------------|
id  | Unique record identifier |
affected_count | Number of data records involved in the breach |
total_amount | Dollar cost of the breach  |
naic_sector | Two digit NAICS code of the industry sector |
naic_national_industry  | Full six-digit NAICS code for the breached company |
sector | Text description of the `naic_sector` field |
breach_date | Date the breach occurred |
cause | High level summary of the cause of the breach |

## Questions

At Cyentia, we use R and the Tidyverse for our work. Feel free to use 
another language/environment if you prefer. Please answer the following 
questions:

1) Visualize the distribution of dollars involved in breaches

2) What is the typical loss (in dollars)?

3) What is the relationship between total_amounts and affected_count?
